project                   = "lambda-vpc-tf"
environment               = "dev"
region                    = "us-east-1"
vpc_cidr_block            = "10.0.0.0/16"
subnet_public_cidr_block  = "10.0.0.0/21"
subnet_private_cidr_block = "10.0.8.0/21"
